import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css';

import CustomInput from '../components/CustomInput';

export default function Home() {

    // useState is a hook
    // hooks are React functions that allow access
    // to special React features
    // const [name, setName] = useState('');

    // assign a variable to an anonymous function
    // const handleUpdateName = (event) => {
    //     // extract value from input from event
    //     const value = event.target.value;

    //     // set the state of name to the
    //     // value of the input
    //     setName(value);
    // };

    const handleUpdateText = (text) => {
        console.log('in the parent we can access the variable text', text);
    };

    const handleSubmit = (text) => {
        console.log('i the parent have seen the submission', text);
    };

    // return html+js = jsx
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <p>Hello { name }</p>
            <input type='text' value={ name } onChange={ handleUpdateName } /> */}
            <CustomInput text='Sarina'
                handleUpdateText={ handleUpdateText }
                handleTextSubmit={ handleSubmit } />
        </div>
    );
}
