import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';

import { useState } from 'react';

import styles from '../styles/Home.module.css';

export default function Home() {

    const router = useRouter();

    const [name, setName] = useState('');
    const [pattern, setPattern] = useState('');
    const [speed, setSpeed] = useState('');
    const [country, setCountry] = useState('');

    const handleNameChange = (event) => {
        const value = event.target.value;

        setName(value);
    };

    const handlePatternChange = (event) => {
        const value = event.target.value;

        setPattern(value);
    };

    const handleSpeedChange = (event) => {
        const value = event.target.value;

        setSpeed(value);
    };

    const handleCountryChange = (event) => {
        const value = event.target.value;

        setCountry(value);
    };

    const handleSubmit = async () => {
        console.log(name);
        console.log(pattern);
        console.log(speed);
        console.log(country);

        const data = {
            name,
            pattern,
            speed,
            country
        };

        const body = JSON.stringify(data);
        const requestOptions = {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body,
        };

        const response = await fetch('http://localhost:3000/api/cheetah', requestOptions);
        const json = await response.json();

        console.log(json);
    };

    const handleSecondPage = () => {
        router.push('/view');
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <p>
                Name <br/>
                <input type='text' value={ name } onChange={ handleNameChange }></input>
            </p>
            <p>
                Pattern <br/>
                <input type='text' value={ pattern } onChange={ handlePatternChange }></input>
            </p>
            <p>
                Speed <br/>
                <input type='text' value={ speed } onChange={ handleSpeedChange }></input>
            </p>
            <p>
                Country <br/>
                <input type='text' value={ country } onChange={ handleCountryChange }></input>
            </p>

            <button onClick={ handleSubmit }>Submit</button>
            <button onClick={ handleSecondPage }>Second Page</button>
            {/* <Link href='/view'>Second Page</Link> */}
        </div>
    );

}