import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';

import { useState } from 'react';

import styles from '../styles/Home.module.css';

export default function Home() {

    const router = useRouter();

    const [name, setName] = useState('');
    const [hairColour, setHairColour] = useState('');
    const [favouriteFood, setFavouriteFood] = useState('');

    const handleNameChange = (event) => {
        const value = event.target.value;

        setName(value);
    };

    const handleHairColourChange = (event) => {
        const value = event.target.value;

        setHairColour(value);
    };

    const handleFavouriteFoodChange = (event) => {
        const value = event.target.value;

        setFavouriteFood(value);
    };

    const handleSubmit = async () => {
        console.log(name);
        console.log(hairColour);
        console.log(favouriteFood);

        const data = {
            name,
            hairColour,
            favouriteFood
        };

        const body = JSON.stringify(data);
        const requestOptions = {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body,
        };

        const response = await fetch('http://localhost:3000/api/flamingo', requestOptions);
        const json = await response.json();

        console.log(json);
    };

    const handleSecondPage = () => {
        router.push('/view');
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <p>
                Name
                <input type='text' value={ name } onChange={ handleNameChange }></input>
            </p>
            <p>
                Hair Colour
                <input type='text' value={ hairColour } onChange={ handleHairColourChange }></input>
            </p>
            <p>
                Favourite Food
                <input type='text' value={ favouriteFood } onChange={ handleFavouriteFoodChange }></input>
            </p>

            <button onClick={ handleSubmit }>Submit</button>
            <button onClick={ handleSecondPage }>Second Page</button>
            {/* <Link href='/view'>Second Page</Link> */}
        </div>
    );

}