import Head from 'next/head';
import Image from 'next/image';
import { getFlamingos } from '../backend/database';
import styles from '../styles/Home.module.css';

import * as cheerio from 'cheerio';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
}

export async function getServerSideProps() {
    const data = await getFlamingos();

    // console.log('the data is', data);
    const response = await fetch('https://bc-cb.rcmp-grc.gc.ca/ViewPage.action?siteNodeId=464&languageId=1&contentId=-1'); 

    // console.log('data', await response.text());
    const html = await response.text();

    // console.log(html);

    const $ = cheerio.load(html);

    // console.log($.html());
    const divs = $('.caption') as any;

    // console.log('divs', divs);

    // /html/body/main/div[2]/div[1]/div[1]/div[1]/figure/figcaption/p[1]
    // /html/body/main/div[2]/div[1]/div[1]/div[2]/figure/figcaption/p[1]
    for (const div of divs) {
        // console.log('divs', div);
        const children = div.children;
        const next = div.next;
        // console.log('children', children);
        // console.log('next', next);

        for (const child of children) {
            // console.log('child is', child);
            if (child.children && child.children.length > 0) {
                const placeName = child.children[0];
                if (placeName.type == 'text') {
                    const data = placeName.data;
                    if (data.startsWith('Published:')) {
                        continue;
                    }

                    console.log('placename is ', data);
                }
            }
        }
    }

    // console.log('the divs are', divs);

    return {
        props: {}
    };
};
